package com.monapp.api.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.Statement;

public class SetupTable {

    private static final Logger log = LoggerFactory.getLogger(SetupTable.class);

    public static void main(String[] args) {
        log.info("Création de la table ANNONCES...");

        String sql = "CREATE TABLE ANNONCES (" +
                     "ID NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
                     "TITRE VARCHAR2(100), " +
                     "PRIX NUMBER, " +
                     "DESCRIPTION VARCHAR2(500), " +
                     "PRIMARY KEY (ID))";

        try (Connection conn = DatabaseManager.getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.execute(sql);
            log.info("Table ANNONCES créée avec succès !");

        } catch (Exception e) {
            if (e.getMessage() != null && e.getMessage().contains("ORA-00955")) {
                log.warn("La table existe déjà (c'est bon signe !).");
            } else {
                log.error("Erreur lors de la création de la table", e);
            }
        }
    }
}
