package com.monapp.api.config;

import java.sql.Connection;
import java.sql.Statement;

public class SetupTable {
    public static void main(String[] args) {
        System.out.println("🔨 Création de la table ANNONCES...");
        
        // Le code SQL pour créer la table
        String sql = "CREATE TABLE ANNONCES (" +
                     "ID NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
                     "TITRE VARCHAR2(100), " +
                     "PRIX NUMBER, " +
                     "DESCRIPTION VARCHAR2(500), " +
                     "PRIMARY KEY (ID))";

        try (Connection conn = DatabaseManager.getConnection();
             Statement stmt = conn.createStatement()) {
            
            stmt.execute(sql);
            System.out.println("✅ Table ANNONCES créée avec succès !");
            
        } catch (Exception e) {
            // Si la table existe déjà, Oracle renverra une erreur spécifique (ORA-00955)
            if (e.getMessage().contains("ORA-00955")) {
                System.out.println("⚠️ La table existe déjà (c'est bon signe !).");
            } else {
                e.printStackTrace();
            }
        }
    }
}